name: ci

on:
  push:
    branches: master

jobs:
  build:
    - name: Checkout step
      uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rubencabrera/dinaip:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
